spring.application.name=user-service
server.port=8081

# Producer configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.port=5672

rabbitmq.exchange.name=user_microservice_exchange

rabbitmq.sms.queue.name=user_sms_queue
rabbitmq.sms.binding.routing.key=user_sms_service_key

rabbitmq.email.queue.name=user_email_queue
rabbitmq.email.binding.routing.key=user_email_service_key
