spring.application.name=rabbitmq-demo
server.port=8080

# Rabbitmq configurations
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Rabbitmq communication configurations for strign message
rabbitmq.queue.name=springboot_app_queue
rabbitmq.exchange.name=springboot_app_exchange
rabbitmq.binding.routing.key=springboot_app_routing_key

# New queue for the employee object
rabbitmq.queue.employee.name=springboot_app_employee_queue
rabbitmq.employee.binding.routing.key=springboot_app_employee_routing_key
